# Generated by Django 5.2.1 on 2025-05-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
