# Generated by Django 5.2.1 on 2025-05-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nombre_empleado_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='horas_extra',
            new_name='horas_extras',
        ),
    ]
