# Generated by Django 5.2.1 on 2025-05-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_horas_extra_rol_horas_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='aniomes',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='bono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='iess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tot_des',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tot_ing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
